// swift-tools-version:5.7

import PackageDescription

let package = Package(
    name: "SwiftyBridgesVapor",
    platforms: [
        .macOS(.v12)
    ],
    products: [
        .library(
            name: "SwiftyBridges",
            targets: ["SwiftyBridges"]),
        .library(
            name: "SwiftyBridgesFluent",
            targets: ["SwiftyBridgesFluent"]),
        .executable(
            name: "BridgeBuilder",
            targets: ["BridgeBuilder"]),
        .plugin(
            name: "APICodeGenerator",
            targets: ["APICodeGenerator"]),
        .plugin(
            name: "XcodeBridgeHelper",
            targets: ["XcodeBridgeHelper"]),
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "4.57.0"),
        .package(url: "https://github.com/vapor/fluent-kit.git", from: "1.35.1"),
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-syntax.git", from: "509.0.0-swift-5.9-DEVELOPMENT-SNAPSHOT-2023-04-25-b"),
        .package(url: "https://github.com/stencilproject/Stencil.git", .upToNextMinor(from: "0.14.1")),
    ],
    targets: [
        .target(
            name: "SwiftyBridges",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
            ]
        ),
        .target(
            name: "SwiftyBridgesFluent",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "FluentKit", package: "fluent-kit"),
            ]
        ),
        .executableTarget(
            name: "BridgeBuilder",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                .product(name: "Stencil", package: "Stencil"),
                .product(name: "SwiftParser", package: "swift-syntax"),
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxBuilder", package: "swift-syntax")
            ],
            resources: [
                .copy("Templates")
            ]
        ),
        .testTarget(
            name: "SwiftyBridgesTests",
            dependencies: ["SwiftyBridges"]
        ),
        .plugin(
            name: "APICodeGenerator",
            capability: .buildTool(),
            dependencies: ["BridgeBuilder"]
        ),
        .plugin(
            name: "XcodeBridgeHelper",
            capability: .command(
                intent: .custom(
                    verb: "xcode-bridge-helper",
                    description: """
                        This command is intended to be called in an Xcode post-build script to surface the generated API client code. To use it, add the following script as a post-build script to the main scheme of your package in Xcode and be sure to select the 'App' target under 'Provide build settings from':
                        
                        # This script is needed to ensure that the API client code generated by SwiftyBridges is updated and made accessible each time the server code is updated and built. After building, you can find it under 'GeneratedClientCode' inside the package directory.
                        cd "$WORKSPACE_PATH"
                        swift package --disable-sandbox xcode-bridge-helper
                        
                        Also consider making the scheme shared and committing it to git (it is located under .swiftpm/xcode in the package folder) so that the script is already configured for other people or when freshly cloning the project.
                        """
                )
            )
        ),
    ]
)
